export const products = [
  {
    id: 1,
    title: "Aluminum Case 44mm",
    class: "watch",
    price: 280,
    image: "../images/1.png",
  },
  {
    id: 2,
    title: "Arctis Pro 2021 Edition",
    class: "headphone",
    price: 590,
    image: "../images/2.png",
  },
  {
    id: 3,
    title: "iPhone 12 Pro Max",
    class: "mobile",
    price: 900,
    image: "../images/3.png",
  },
  {
    id: 4,
    title: "Galaxy S21 Ultra",
    class: "mobile",
    price: 830,
    image: "../images/4.png",
  },
  {
    id: 5,
    title: "Galaxy Note20 Ultra",
    class: "mobile",
    price: 800,
    image: "../images/5.png",
  },
  {
    id: 6,
    title: "MacBook Pro MYD82",
    class: "laptop",
    price: 1250,
    image: "../images/6.png",
  },
  {
    id: 7,
    title: "iPhone 11",
    class: "mobile",
    price: 750,
    image: "../images/7.jpg",
  },
  {
    id: 8,
    title: "ZenBook 14 UM425IA",
    class: "laptop",
    price: 930,
    image: "../images/8.png",
  },
  {
    id: 9,
    title: "Beyerdynamic Lagoon",
    class: "headphone",
    price: 720,
    image: "../images/9.jpg",
  },
  {
    id: 10,
    title: "Galaxy Watch Active2 44mm",
    class: "watch",
    price: 310,
    image: "../images/10.jpg",
  },
  {
    id: 11,
    title: "AirPods Max",
    class: "headphone",
    price: 860,
    image: "../images/11.png",
  },
  {
    id: 12,
    title: "Level On",
    class: "headphone",
    price: 540,
    image: "../images/12.png",
  },
  {
    id: 13,
    title: "Galaxy Watch Active2 44mm",
    class: "watch",
    price: 310,
    image: "../images/13.png",
  },
  {
    id: 14,
    title: "Nova 7i JNY-LX1",
    class: "mobile",
    price: 490,
    image: "../images/14.png",
  },
];
